[2022-01-03 00:01:39,263] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.pre_process_image manual__2022-01-03T00:01:03.428846+00:00 [queued]>
[2022-01-03 00:01:39,280] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.pre_process_image manual__2022-01-03T00:01:03.428846+00:00 [queued]>
[2022-01-03 00:01:39,281] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 00:01:39,281] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-03 00:01:39,282] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 00:01:39,308] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): pre_process_image> on 2022-01-03 00:01:03.428846+00:00
[2022-01-03 00:01:39,313] {standard_task_runner.py:52} INFO - Started process 1405 to run task
[2022-01-03 00:01:39,319] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'pre_process_image', 'manual__2022-01-03T00:01:03.428846+00:00', '--job-id', '1951', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpwtan2r_5', '--error-file', '/tmp/tmp0mfwg5xo']
[2022-01-03 00:01:39,320] {standard_task_runner.py:77} INFO - Job 1951: Subtask pre_process_image
[2022-01-03 00:01:39,380] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.pre_process_image manual__2022-01-03T00:01:03.428846+00:00 [running]> on host 218df5ddc363
[2022-01-03 00:01:39,444] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=pre_process_image
AIRFLOW_CTX_EXECUTION_DATE=2022-01-03T00:01:03.428846+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-03T00:01:03.428846+00:00
[2022-01-03 00:01:39,446] {python.py:152} INFO - Done. Returned value was: None
[2022-01-03 00:01:39,459] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=pre_process_image, execution_date=20220103T000103, start_date=20220103T000139, end_date=20220103T000139
[2022-01-03 00:01:39,490] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-03 00:01:39,554] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
