[2021-12-08 14:42:37,721] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.pre_process scheduled__2021-07-03T00:00:00+00:00 [queued]>
[2021-12-08 14:42:37,855] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.pre_process scheduled__2021-07-03T00:00:00+00:00 [queued]>
[2021-12-08 14:42:37,859] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 14:42:37,866] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-08 14:42:37,868] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 14:42:38,103] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): pre_process> on 2021-07-03 00:00:00+00:00
[2021-12-08 14:42:38,122] {standard_task_runner.py:52} INFO - Started process 153 to run task
[2021-12-08 14:42:38,134] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'pre_process', 'scheduled__2021-07-03T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpokop9enn', '--error-file', '/tmp/tmpg9amrbcf']
[2021-12-08 14:42:38,136] {standard_task_runner.py:77} INFO - Job 99: Subtask pre_process
[2021-12-08 14:42:38,399] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.pre_process scheduled__2021-07-03T00:00:00+00:00 [running]> on host 6ff10d26dc07
[2021-12-08 14:42:38,846] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=pre_process
AIRFLOW_CTX_EXECUTION_DATE=2021-07-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-03T00:00:00+00:00
[2021-12-08 14:43:08,329] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:162: DtypeWarning: Columns (0,1,2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2021-12-08 14:43:09,286] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2021-12-08 14:43:09,716] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=cpp_workflow, task_id=pre_process, execution_date=20210703T000000, start_date=20211208T144237, end_date=20211208T144309
[2021-12-08 14:43:10,678] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
