[2021-12-08 15:01:18,132] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_file scheduled__2021-11-05T00:00:00+00:00 [queued]>
[2021-12-08 15:01:18,309] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_file scheduled__2021-11-05T00:00:00+00:00 [queued]>
[2021-12-08 15:01:18,324] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 15:01:18,338] {taskinstance.py:1242} INFO - Starting attempt 1 of 3
[2021-12-08 15:01:18,355] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 15:01:18,540] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): check_file> on 2021-11-05 00:00:00+00:00
[2021-12-08 15:01:18,579] {standard_task_runner.py:52} INFO - Started process 1042 to run task
[2021-12-08 15:01:18,623] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'check_file', 'scheduled__2021-11-05T00:00:00+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp2z3hnku6', '--error-file', '/tmp/tmpy1i57_2z']
[2021-12-08 15:01:18,625] {standard_task_runner.py:77} INFO - Job 372: Subtask check_file
[2021-12-08 15:01:22,892] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.check_file scheduled__2021-11-05T00:00:00+00:00 [running]> on host 8edf9af2b560
[2021-12-08 15:01:23,552] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=check_file
AIRFLOW_CTX_EXECUTION_DATE=2021-11-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-05T00:00:00+00:00
[2021-12-08 15:01:23,618] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-08 15:01:23,625] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sha256sum /opt/***/official_data/test.csv']
[2021-12-08 15:01:24,103] {subprocess.py:85} INFO - Output:
[2021-12-08 15:01:34,977] {subprocess.py:89} INFO - 6658e41458ff02775f57e8d8f407a0e62966d5cf65680690cb8da28db866e38c  /opt/***/official_data/test.csv
[2021-12-08 15:01:35,007] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-08 15:01:35,458] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=check_file, execution_date=20211105T000000, start_date=20211208T150118, end_date=20211208T150135
[2021-12-08 15:01:35,564] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-08 15:01:35,815] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
