[2021-12-29 10:44:34,031] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.merge_process scheduled__2021-12-28T00:00:00+00:00 [queued]>
[2021-12-29 10:44:34,048] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.merge_process scheduled__2021-12-28T00:00:00+00:00 [queued]>
[2021-12-29 10:44:34,048] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 10:44:34,049] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-29 10:44:34,049] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 10:44:34,065] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): merge_process> on 2021-12-28 00:00:00+00:00
[2021-12-29 10:44:34,069] {standard_task_runner.py:52} INFO - Started process 97 to run task
[2021-12-29 10:44:34,075] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'merge_process', 'scheduled__2021-12-28T00:00:00+00:00', '--job-id', '1636', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp0ww0o15u', '--error-file', '/tmp/tmpjy08jvd5']
[2021-12-29 10:44:34,077] {standard_task_runner.py:77} INFO - Job 1636: Subtask merge_process
[2021-12-29 10:44:34,146] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.merge_process scheduled__2021-12-28T00:00:00+00:00 [running]> on host 218df5ddc363
[2021-12-29 10:44:34,287] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=merge_process
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-28T00:00:00+00:00
[2021-12-29 10:44:34,478] {python.py:152} INFO - Done. Returned value was: None
[2021-12-29 10:44:34,513] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=merge_process, execution_date=20211228T000000, start_date=20211229T104434, end_date=20211229T104434
[2021-12-29 10:44:34,569] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-29 10:44:34,700] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
