[2021-12-15 16:25:11,049] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.merge_process manual__2021-12-15T16:24:57.805303+00:00 [queued]>
[2021-12-15 16:25:11,126] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.merge_process manual__2021-12-15T16:24:57.805303+00:00 [queued]>
[2021-12-15 16:25:11,128] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-15 16:25:11,130] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-15 16:25:11,131] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-15 16:25:11,181] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): merge_process> on 2021-12-15 16:24:57.805303+00:00
[2021-12-15 16:25:11,197] {standard_task_runner.py:52} INFO - Started process 255 to run task
[2021-12-15 16:25:11,208] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'merge_process', 'manual__2021-12-15T16:24:57.805303+00:00', '--job-id', '1405', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpqm5nmn56', '--error-file', '/tmp/tmpb8ri_x7_']
[2021-12-15 16:25:11,211] {standard_task_runner.py:77} INFO - Job 1405: Subtask merge_process
[2021-12-15 16:25:11,326] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.merge_process manual__2021-12-15T16:24:57.805303+00:00 [running]> on host 218df5ddc363
[2021-12-15 16:25:11,404] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=merge_process
AIRFLOW_CTX_EXECUTION_DATE=2021-12-15T16:24:57.805303+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-15T16:24:57.805303+00:00
[2021-12-15 16:25:11,518] {python.py:152} INFO - Done. Returned value was: None
[2021-12-15 16:25:11,538] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=merge_process, execution_date=20211215T162457, start_date=20211215T162511, end_date=20211215T162511
[2021-12-15 16:25:11,581] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-15 16:25:11,630] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
