[2022-01-03 02:08:16,339] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.col_process_image manual__2022-01-03T02:08:09.464942+00:00 [queued]>
[2022-01-03 02:08:16,354] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.col_process_image manual__2022-01-03T02:08:09.464942+00:00 [queued]>
[2022-01-03 02:08:16,355] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 02:08:16,355] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-03 02:08:16,355] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 02:08:16,374] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): col_process_image> on 2022-01-03 02:08:09.464942+00:00
[2022-01-03 02:08:16,379] {standard_task_runner.py:52} INFO - Started process 7962 to run task
[2022-01-03 02:08:16,384] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'col_process_image', 'manual__2022-01-03T02:08:09.464942+00:00', '--job-id', '2318', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpq03idt2m', '--error-file', '/tmp/tmpg45j_xhl']
[2022-01-03 02:08:16,385] {standard_task_runner.py:77} INFO - Job 2318: Subtask col_process_image
[2022-01-03 02:08:16,436] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.col_process_image manual__2022-01-03T02:08:09.464942+00:00 [running]> on host 218df5ddc363
[2022-01-03 02:08:16,502] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=col_process_image
AIRFLOW_CTX_EXECUTION_DATE=2022-01-03T02:08:09.464942+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-03T02:08:09.464942+00:00
[2022-01-03 02:08:16,504] {python.py:152} INFO - Done. Returned value was: None
[2022-01-03 02:08:16,603] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=col_process_image, execution_date=20220103T020809, start_date=20220103T020816, end_date=20220103T020816
[2022-01-03 02:08:16,638] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-03 02:08:16,706] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
