[2021-12-09 00:38:49,177] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.merge_process manual__2021-12-09T00:38:38.596062+00:00 [queued]>
[2021-12-09 00:38:49,190] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.merge_process manual__2021-12-09T00:38:38.596062+00:00 [queued]>
[2021-12-09 00:38:49,191] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-09 00:38:49,191] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-09 00:38:49,191] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-09 00:38:49,206] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): merge_process> on 2021-12-09 00:38:38.596062+00:00
[2021-12-09 00:38:49,212] {standard_task_runner.py:52} INFO - Started process 10067 to run task
[2021-12-09 00:38:49,215] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'merge_process', 'manual__2021-12-09T00:38:38.596062+00:00', '--job-id', '747', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpqrf7u1pi', '--error-file', '/tmp/tmp3txpmaq_']
[2021-12-09 00:38:49,216] {standard_task_runner.py:77} INFO - Job 747: Subtask merge_process
[2021-12-09 00:38:49,260] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.merge_process manual__2021-12-09T00:38:38.596062+00:00 [running]> on host b5fd0372bf6e
[2021-12-09 00:38:49,310] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=merge_process
AIRFLOW_CTX_EXECUTION_DATE=2021-12-09T00:38:38.596062+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-09T00:38:38.596062+00:00
[2021-12-09 00:38:49,727] {python.py:152} INFO - Done. Returned value was: None
[2021-12-09 00:38:49,744] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=merge_process, execution_date=20211209T003838, start_date=20211209T003849, end_date=20211209T003849
[2021-12-09 00:38:49,790] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-09 00:38:49,837] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
