[2021-12-29 23:48:22,964] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.col_process_image manual__2021-12-29T23:47:51.234749+00:00 [queued]>
[2021-12-29 23:48:22,985] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.col_process_image manual__2021-12-29T23:47:51.234749+00:00 [queued]>
[2021-12-29 23:48:22,985] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 23:48:22,986] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-29 23:48:22,986] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 23:48:23,008] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): col_process_image> on 2021-12-29 23:47:51.234749+00:00
[2021-12-29 23:48:23,015] {standard_task_runner.py:52} INFO - Started process 15455 to run task
[2021-12-29 23:48:23,020] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'col_process_image', 'manual__2021-12-29T23:47:51.234749+00:00', '--job-id', '1739', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpbvrg12ld', '--error-file', '/tmp/tmp58bmu4jr']
[2021-12-29 23:48:23,022] {standard_task_runner.py:77} INFO - Job 1739: Subtask col_process_image
[2021-12-29 23:48:23,096] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.col_process_image manual__2021-12-29T23:47:51.234749+00:00 [running]> on host 218df5ddc363
[2021-12-29 23:48:23,251] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=col_process_image
AIRFLOW_CTX_EXECUTION_DATE=2021-12-29T23:47:51.234749+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-29T23:47:51.234749+00:00
[2021-12-29 23:48:23,265] {python.py:152} INFO - Done. Returned value was: None
[2021-12-29 23:48:23,343] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=col_process_image, execution_date=20211229T234751, start_date=20211229T234822, end_date=20211229T234823
[2021-12-29 23:48:23,403] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-29 23:48:23,480] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
