[2022-01-16 11:47:36,139] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.delete_working_files scheduled__2022-01-15T00:00:00+00:00 [queued]>
[2022-01-16 11:47:36,148] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.delete_working_files scheduled__2022-01-15T00:00:00+00:00 [queued]>
[2022-01-16 11:47:36,148] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-16 11:47:36,148] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-16 11:47:36,149] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-16 11:47:36,159] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): delete_working_files> on 2022-01-15 00:00:00+00:00
[2022-01-16 11:47:36,162] {standard_task_runner.py:52} INFO - Started process 115 to run task
[2022-01-16 11:47:36,164] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'delete_working_files', 'scheduled__2022-01-15T00:00:00+00:00', '--job-id', '2729', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmps47ly93s', '--error-file', '/tmp/tmpc77rbc5s']
[2022-01-16 11:47:36,165] {standard_task_runner.py:77} INFO - Job 2729: Subtask delete_working_files
[2022-01-16 11:47:36,196] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.delete_working_files scheduled__2022-01-15T00:00:00+00:00 [running]> on host 218df5ddc363
[2022-01-16 11:47:36,236] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=delete_working_files
AIRFLOW_CTX_EXECUTION_DATE=2022-01-15T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-15T00:00:00+00:00
[2022-01-16 11:47:36,255] {python.py:152} INFO - Done. Returned value was: None
[2022-01-16 11:47:36,265] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=delete_working_files, execution_date=20220115T000000, start_date=20220116T114736, end_date=20220116T114736
[2022-01-16 11:47:36,297] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-16 11:47:36,320] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
