[2021-12-08 17:13:05,785] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.pre_process manual__2021-12-08T17:12:55.513095+00:00 [queued]>
[2021-12-08 17:13:05,798] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.pre_process manual__2021-12-08T17:12:55.513095+00:00 [queued]>
[2021-12-08 17:13:05,799] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 17:13:05,799] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-08 17:13:05,799] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 17:13:05,819] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): pre_process> on 2021-12-08 17:12:55.513095+00:00
[2021-12-08 17:13:05,824] {standard_task_runner.py:52} INFO - Started process 318 to run task
[2021-12-08 17:13:05,828] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'pre_process', 'manual__2021-12-08T17:12:55.513095+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpgflqlf9o', '--error-file', '/tmp/tmpmttemark']
[2021-12-08 17:13:05,830] {standard_task_runner.py:77} INFO - Job 460: Subtask pre_process
[2021-12-08 17:13:05,882] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.pre_process manual__2021-12-08T17:12:55.513095+00:00 [running]> on host 8edf9af2b560
[2021-12-08 17:13:05,951] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=pre_process
AIRFLOW_CTX_EXECUTION_DATE=2021-12-08T17:12:55.513095+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-08T17:12:55.513095+00:00
[2021-12-08 17:13:10,809] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:162: DtypeWarning: Columns (0,1,2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2021-12-08 17:13:12,587] {python.py:152} INFO - Done. Returned value was: None
[2021-12-08 17:13:12,602] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=pre_process, execution_date=20211208T171255, start_date=20211208T171305, end_date=20211208T171312
[2021-12-08 17:13:12,670] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-08 17:13:12,712] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
