[2022-01-10 13:34:00,471] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.update_processed_files_media_prepare manual__2022-01-10T13:33:36.639179+00:00 [queued]>
[2022-01-10 13:34:00,489] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.update_processed_files_media_prepare manual__2022-01-10T13:33:36.639179+00:00 [queued]>
[2022-01-10 13:34:00,489] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-10 13:34:00,490] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-10 13:34:00,491] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-10 13:34:00,517] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): update_processed_files_media_prepare> on 2022-01-10 13:33:36.639179+00:00
[2022-01-10 13:34:00,525] {standard_task_runner.py:52} INFO - Started process 1888 to run task
[2022-01-10 13:34:00,532] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'update_processed_files_media_prepare', 'manual__2022-01-10T13:33:36.639179+00:00', '--job-id', '2611', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp6mezfdo5', '--error-file', '/tmp/tmpbvl1r7zi']
[2022-01-10 13:34:00,534] {standard_task_runner.py:77} INFO - Job 2611: Subtask update_processed_files_media_prepare
[2022-01-10 13:34:00,626] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.update_processed_files_media_prepare manual__2022-01-10T13:33:36.639179+00:00 [running]> on host 218df5ddc363
[2022-01-10 13:34:00,781] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=update_processed_files_media_prepare
AIRFLOW_CTX_EXECUTION_DATE=2022-01-10T13:33:36.639179+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-10T13:33:36.639179+00:00
[2022-01-10 13:34:00,815] {python.py:152} INFO - Done. Returned value was: None
[2022-01-10 13:34:00,840] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=update_processed_files_media_prepare, execution_date=20220110T133336, start_date=20220110T133400, end_date=20220110T133400
[2022-01-10 13:34:00,909] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-10 13:34:01,002] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
