[2021-12-08 15:00:41,340] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_file scheduled__2021-11-02T00:00:00+00:00 [queued]>
[2021-12-08 15:00:41,408] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: cpp_workflow.check_file scheduled__2021-11-02T00:00:00+00:00 [queued]>
[2021-12-08 15:00:41,416] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 15:00:41,424] {taskinstance.py:1242} INFO - Starting attempt 1 of 3
[2021-12-08 15:00:41,451] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 15:00:41,545] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): check_file> on 2021-11-02 00:00:00+00:00
[2021-12-08 15:00:41,609] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cpp_workflow', 'check_file', 'scheduled__2021-11-02T00:00:00+00:00', '--job-id', '366', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp3cm02zyq', '--error-file', '/tmp/tmpzh_r1hj5']
[2021-12-08 15:00:41,613] {standard_task_runner.py:77} INFO - Job 366: Subtask check_file
[2021-12-08 15:00:41,573] {standard_task_runner.py:52} INFO - Started process 1001 to run task
[2021-12-08 15:00:41,949] {logging_mixin.py:109} INFO - Running <TaskInstance: cpp_workflow.check_file scheduled__2021-11-02T00:00:00+00:00 [running]> on host 8edf9af2b560
[2021-12-08 15:00:42,377] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cpp_workflow
AIRFLOW_CTX_TASK_ID=check_file
AIRFLOW_CTX_EXECUTION_DATE=2021-11-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-02T00:00:00+00:00
[2021-12-08 15:00:42,390] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-08 15:00:42,394] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sha256sum /opt/***/official_data/test.csv']
[2021-12-08 15:00:42,585] {subprocess.py:85} INFO - Output:
[2021-12-08 15:00:57,429] {subprocess.py:89} INFO - 6658e41458ff02775f57e8d8f407a0e62966d5cf65680690cb8da28db866e38c  /opt/***/official_data/test.csv
[2021-12-08 15:00:57,439] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-08 15:00:58,203] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=cpp_workflow, task_id=check_file, execution_date=20211102T000000, start_date=20211208T150041, end_date=20211208T150058
[2021-12-08 15:00:58,422] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-08 15:00:58,878] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
